In [12]:
import numpy as np

In [13]:
a = np.ones(6)
b = np.ones(6)

In [14]:
a * b

array([1., 1., 1., 1., 1., 1.])

In [15]:
a

array([1., 1., 1., 1., 1., 1.])

In [16]:
b

array([1., 1., 1., 1., 1., 1.])